version: "3.8"

services:
  app:
    image: devalth/todo-app:qa  # ✅ QA-specific image
    container_name: fastapi_todo
    restart: always
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/todo_db
    ports:
      - "8001:8000"
    networks:
      - todo_network

networks:
  todo_network:
    external: true  # ✅ Connect to existing persistent db/pgadmin