version: '3.9'

services:
  db:
    image: postgres:15
    container_name: todo_postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: todo_db
    ports:
      - "5433:5432"  # Host:Container
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistent database storage

  app:
    build: .
    container_name: fastapi_todo
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/todo_db
    ports:
      - "8000:8000"  # FastAPI running on 8000
    volumes:
      - .:/app  # Bind source code for development
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]  # Auto-reload for dev

  pgadmin:
    image: dpage/pgadmin4
    container_name: todo_pgadmin
    restart: always
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com  # Admin login for pgAdmin
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"  # pgAdmin available on localhost:5050
    volumes:
      - pgadmin_data:/var/lib/pgadmin  # Persistent pgAdmin settings

  jenkins:
    image: jenkins/jenkins:lts-docker  # ✅ Jenkins image with Docker pre-installed
    container_name: todo_jenkins
    restart: always
    ports:
      - "8181:8080"  # Jenkins Web UI on localhost:8181
      - "50000:50000"  # Jenkins agent port
    privileged: true  # ✅ Required to access Docker daemon
    user: root  # Run as root to use Docker socket
    volumes:
      - jenkins_home:/var/jenkins_home  # Persistent Jenkins data
      - ./jenkins_plugins:/usr/share/jenkins/ref/plugins  # Pre-load Jenkins plugins (Optional)
      - /var/run/docker.sock:/var/run/docker.sock  # ✅ Critical for Docker commands in Jenkins pipelines
    environment:
      JAVA_OPTS: -Djenkins.install.runSetupWizard=false  # Skip initial setup wizard (Optional)

volumes:
  postgres_data:
  pgadmin_data:
  jenkins_home: