version: "3.8"

services:
  app:
    image: devalth/todo-app:develop
    container_name: fastapi_todo_develop
    restart: always
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/todo_db
    ports:
      - "8000:8000"
    networks:
      - todo_network

networks:
  todo_network:
    external: true