version: "3.8"

services:
  db:
    image: postgres:15
    container_name: todo_postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: todo_db
    ports:
      - "5435:5432"  # Prod DB port
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: devalth/todo-app:main  # ✅ Main/Prod image
    container_name: fastapi_todo
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/todo_db
    ports:
      - "8002:8000"

  pgadmin:
    image: dpage/pgadmin4
    container_name: todo_pgadmin
    restart: always
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5052:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data: