version: "3.8"

services:
  db:
    image: postgres:15
    container_name: todo_postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: todo_db
    ports:
      - "5433:5432"  # Keep this fixed for DB access
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - todo_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: todo_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - todo_network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  todo_network:
    external: true