version: '3.9'

services:
  db:
    image: postgres:15
    container_name: todo_postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: todo_db
    ports:
      - "5433:5432"  # Host:Container
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: fastapi_todo
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@db:5432/todo_db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  pgadmin:
    image: dpage/pgadmin4
    container_name: todo_pgadmin
    restart: always
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  jenkins:
    image: jenkins/jenkins:lts
    container_name: todo_jenkins
    restart: always
    ports:
      - "8181:8080"  # Jenkins UI accessible at localhost:8181
      - "50000:50000"  # For Jenkins agents
    privileged: true  # To allow Docker inside Jenkins
    user: root
    volumes:
      - jenkins_home:/var/jenkins_home  # Persistent Jenkins data
      - ./jenkins_plugins:/usr/share/jenkins/ref/plugins  # Pre-load Jenkins plugins on first start
      - /var/run/docker.sock:/var/run/docker.sock  # Access to Docker daemon for Jenkins
    environment:
      JAVA_OPTS: -Djenkins.install.runSetupWizard=false  # Optional: Skip setup wizard

volumes:
  postgres_data:
  pgadmin_data:
  jenkins_home: