apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-deployment
  namespace: NAMESPACE_PLACEHOLDER  # ✅ Important for branch-wise isolation
  labels:
    app: todo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: IMAGE_PLACEHOLDER  # ✅ Dynamic via Jenkins
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql://myuser:mypassword@db:5432/TodoAppDatabase"