apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-deployment
  namespace: NAMESPACE_PLACEHOLDER  # ✅ Dynamic via Jenkins
  labels:
    app: todo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - name: todo-app
        image: IMAGE_PLACEHOLDER  # ✅ Dynamic image via Jenkins
        ports:
        - containerPort: 8000
        env:
          - name: DATABASE_URL
            value: "postgresql://myuser:mypassword@db.NAMESPACE_PLACEHOLDER.svc.cluster.local:5432/TodoAppDatabase"